workspace:
  base: /python
  path: github.com/tr-projects-rest
pipeline:
  start_slack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: tr-projects-rest
    icon_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/240px-Python-logo-notext.svg.png
    template: >
      *start* building *{{repo.name}}*.
      *{{build.author}}* give *{{build.branch}}* a little push.
    when:
      event: [push]
      branch: [master, dev]
  
  get_config:
    image: gcr.io/mirrormedia-1470651750304/drone-cloud-sdk:latest
    secrets: [google_credentials]
    commands:
    - gcloud source repos clone configs mm_configs
    - cp -r mm_configs/mirror-media/tr-projects-rest/configs ./configs
    - rm -rf mm_configs
    when:
      event: [push]
      branch: [master, dev]
  
#  builds:
#    image: plugins/gcr
#    repo: mirrormedia-1470651750304/${DRONE_REPO_NAME}
#    tag: ${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER}
#    environment:
#      - DOCKER_LAUNCH_DEBUG=true
#    secrets: [google_credentials]
#    when:
#      event: [push]
#      branch: [master, dev]
  
  deploy_dev:
    image: nytimes/drone-gke
    zone: asia-east1-a
    cluster: dev
    namespace: default
    # For debugging
    dry_run: false
    verbose: true
    secrets:
      - source: google_credentials
        target: token
    vars:
#      image: gcr.io/mirrormedia-1470651750304/${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER}
      image: gcr.io/mirrormedia-1470651750304/${DRONE_REPO_NAME}:dev_b68e695
      app: mm-rest
      tier: backend
      serviceName: rest-service
      deployName: rest-deployment
    when:
      event: [push]
      branch: dev

  finish_slack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: tr-projects-rest
    icon_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/240px-Python-logo-notext.svg.png
    when:
      status: [success, failure]
      event: [push]
      branch: [master, dev]
    template: >
      {{#success build.status}}
        Build<${DRONE_BUILD_LINK}|#{{build.number}}> *success* ${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER} was well served.
        Check out our new <https://gcr.io/mirrormedia-1470651750304/readr-restful|rest>
      {{else}}
        Houston, we have a problem. Build <${DRONE_BUILD_LINK}|#{{build.number}}> failed. Fix me please, {{build.author}}
      {{/success}}
