steps:                                                                                                                                                                  
  - name: gcr.io/cloud-builders/gcloud
    args:
      - source
      - repos
      - clone
      - github_mirror-media_kubernetes-configs
      - ./dockerignore/kubernetes-configs

  - name: bash
    args:
      - ls 
      - /workspace/

  - name: bash
    args:
      - cp
      - >-
        ./dockerignore/kubernetes-configs/tr-projects-rest/overlays/${BRANCH_NAME}/configs/settings.py
      - /workspace/settings.py

  - name: bash
    args:
      - cp
      - "-r"
      - >-
        ./dockerignore/kubernetes-configs/tr-projects-rest/overlays/${BRANCH_NAME}/configs
      - /workspace/

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "gcr.io/${PROJECT_ID}/tr-projects-rest:${BRANCH_NAME}_${SHORT_SHA}"
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "gcr.io/${PROJECT_ID}/tr-projects-rest:${BRANCH_NAME}_${SHORT_SHA}"

  # Deploy container image to Cloud Runs
  - name: gcr.io/cloud-builders/gcloud
    id: Deploy Image
    entrypoint: 'bash'
    args:
      - '-c'
      - |

        # deploy cloud run service
        gcloud run deploy youtube-restful-api --image gcr.io/${PROJECT_ID}/tr-projects-rest:${BRANCH_NAME}_${SHORT_SHA} --region asia-east1

timeout: 300s
